spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mysql:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.100.1.100:3306/springboot?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
        postgres:
          driverClassName: org.postgresql.Driver
          url: jdbc:postgresql://172.100.1.100:5432/springboot
          username: springboot
          password: springboot
  # liquibase config
  liquibase:
    mysql:
      change-log: classpath:db/changelog/mysql/db.changelog-master.xml
      enabled: true
    postgres:
      change-log: classpath:db/changelog/postgres/db.changelog-master.xml
      enabled: true