server:
  port: 8090

spring:
  application:
    name: TreeNode
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.100.1.100:3306/springboot?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Root@123#

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  map-underscore-to-camel-case: true

logging:
  level:
    org.iproute.springboot.design.mysqltree.mapper: debug