server:
  port: 9222

spring:
  application:
    name: boot-search


elasticsearch:
  host: 127.0.0.1
  port: 9200
  scheme: http

management:
  health:
    elasticsearch:
      enabled: false

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace