server:
  port: 8090

spring:
  application:
    name: TreeNode
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    include:
      - datasource

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  map-underscore-to-camel-case: true

logging:
  level:
    org.iproute.springboot.design.tree.mapper.: debug