server:
  port: 8090

spring:
  application:
    name: generic
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    include:
      - datasource
      - redis
      - mybatis
      - actuator