server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:postgresql://172.100.1.100:5432/pg_json
    username: postgres
    password: postgres

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    org.iproute.pg.json.mapper: debug