server:
  port: 8091

spring:
  data:
    redis:
      host: 172.100.1.100
      port: 6379
      password: root
      lettuce:
        pool:
          # 连接池最大连接数(使用负值表示没有限制) 默认为8
          max-active: 8
          # 连接池中的最大空闲连接 默认为8
          max-idle: 8
          # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
          max-wait: -1ms
          # 连接池中的最小空闲连接 默认为 0
          min-idle: 0
    #      sentinel:
    #        master: redis-master
    #        nodes:
    #          - 172.100.1.191:26379
    #          - 172.100.1.192:26379
    #          - 172.100.1.193:26379
#    redisson:
#      # file ?
#      file: classpath:redisson_single.yaml.yaml