server:
  port: 8091

spring:
  application:
    name: tree-node
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    include:
      - datasource

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  # map-underscore-to-camel-case: true

logging:
  level:
    #    root: debug
    web: debug
    org.iproute.springboot.design.tree.mapper: debug